export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const GET_USER_DETAILS_START='GET_USER_DETAILS_START';
export const GET_USER_DETAILS_SUCCESS='GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL='GET_USER_DETAILS_FAIL';

export const SHOW_SIGNIN_OR_SIGNIN= 'SHOW_SIGNIN_OR_SIGNIN';
